name = "Zenarchist's Leftovers Mod"; // name
picture = "ZenLeftovers\data\zenarchist_leftovers.edds"; // picture in expanded description
logoSmall = "ZenLeftovers\data\zenarchist_leftovers.edds"; // icon next to mod name when description is not expanded
logo = "ZenLeftovers\data\zenarchist_leftovers.edds"; // logo below game menu
logoOver = "ZenLeftovers\data\zenarchist_leftovers.edds"; // on mouse hover over logo
tooltip = "Zenarchist's Leftovers Mod"; // tool tip on mouse hover
overview = "Drops leftover discarded food items on the ground for tracking player activity."; // overview
action = "https://zenarchist.io/"; // link
author = "Zenarchist"; // author
version = "1.0"; // version